#!/bin/sh

test -f $WALL || {
    test -f /tmp/grandom || {
        grandom;
        echo 1 >/tmp/grandom;
    }
    exit 1;
}

if [ $(lsw | wc -l) -eq 0 ]; then
    BLUR=0;
else
    BLUR=${1:-10};
fi

hsetroot -fill $WALL -blur $BLUR;
