#!/bin/sh

. util.sh
ARGS="[<x> <y>]"

test $# -eq 0 && {
    reads x y -- wmp;
} || {
    test $# -eq 2 || usage $ERRARG;
    x=$1; y=$2;
}

if wid=$(wup $x $y); then
    fw -r $wid;
else
    # over root window
    echo IMPLEMENT ME >&2;
fi
