#!/bin/dash

. $WMRC
ARGS="[<x> <y>]"

test $# -eq 0 && {
    read x y << end
    $(wmp)
end
} || {
    test $# -eq 2 || usage $ERRARG;
    x=$1; y=$2;
}

if wid=$(wup $x $y); then
    fw $wid;
    chwso -r $wid;
else
    # Over root
    echo TODO: dmenu this ish
fi
