#!/bin/dash
# panel -- hud is a better name.
# deal with it.
# vim:ft=sh

if wid clock > /dev/null; then
    printf '%s\n' "clock is already running" >&2;
    exit 1
fi

datetime() {
    while true; do
        printf '%s %s' '%{l}' \
            '%{A:wenu:}w%{A}';
        date +'%%{c}%a %H:%M';
        sleep 30;
    done
}

# GEOMETRY HARDCODED
datetime | \
    lemonbar -d -f "Luxi Mono:size=10" -n hud \
    -B#dd222222 -F#ddd \
    | sh &

wait;
