#!/bin/dash
# Focus Window

. $WMRC
ARGS="<wid>";

SLOPPY_RAISE=${SLOPPY_RAISE:-0};

setborder() { # <focus|normal> <wid>
    # TODO: expand to allow for arbitrary color schemes
    set -u;
    test $# -eq 2 || return $ERRARG;
    wattr $2 || return $ERRWIN;
    test "$(wattr xywh $2)" != "$(wattr xywh $WRT)" || return $ERRWIN;
    chwb -s $BorderWidth $2;
    case $1 in
        focus)
            chwb2 -I $FocusColor -O $OuterColor \
                  -i $InnerBorder -o $OuterBorder $2
            ;;
        normal)
            chwb2 -I $NormColor -O $OuterColor \
                  -i $InnerBorder -o $OuterBorder $2
            ;;
    esac
}

focid() { # <wid>
    wattr $1 2>/dev/null || {
        usage $ERRWIN "Can't find window '$wid'";
    }
    setborder normal $PFW;
    setborder focus  $1;
    test $SLOPPY_RAISE -eq 1 && chwso -r $1;
    wtf $1;
}

test $# -eq 0 && { focid $PFW; exit $SUCCESS; }
test "$1" = "-r" && { SLOPPY_RAISE=1; shift; }

case "$1" in
    0x*) focid $1 ;;
    *)   isExecutable $1 || exit $ERREXE;
         focid $($@);
    ;;
esac
