#!/bin/sh
# Handle EVents

# restart() {
#     exec $(realpath $0);
# }
# trap restart USR1;
trap 'exit 1' USR2;

wew | while IFS=: read ev wid; do
    . $WMRC;
    case $ev in
        7) # XCB_ENTER_NOTIFY
            if [ $SLOPPY -eq 1 ]; then
                wattr o $wid || {
                    fw $wid;
                }
            fi
            ;;
        16) # XCB_CREATE_NOTIFY
            case "$(wi name $wid)" in
                hud)
                    chwb -s 0 $wid;
                    chwso -r $wid;
                    ignw -s $wid;
                    ;;
            *) case "$(wi class $wid)" in
               *) # default
                wattr o $wid || {
                    fw $wid;
                }
               ;;
               esac
               ;;
            esac
            ;;
        19) # XCB_MAP_NOTIFY
            case "$(wi name $wid)" in
            *) case "$(wi class $wid)" in
                dmenu)
                    chwso -r $wid;
                    ignw -s $wid;
                    ;;
                mpv)
                    wtp $(wattr xywh $WRT);
                    # placew $wid;
                    chwb -s 0 $wid;
                    ;;
               *) # default
                   blur;
               ;;
               esac
               ;;
            esac
            ;;
        17) # XCB_DESTROY_NOTIFY
            ;;
        18) # XCB_UNMAP_NOTIFY
            case "$(wi name $wid)" in
            *) case "$(wi class $wid)" in
               *) # default
                blur;
                wattr "$(pfw)" || fw prev;
               ;;
               esac
               ;;
            esac
            ;;
    esac
done
