#!/bin/sh
# Handle EVents

restart() {
    exec $(realpath $0);
}
trap restart USR1;
. util.sh;

wew -m $((16+32+4194304)) | while IFS=: read ev wid atom; do
    . $WMRC;
    case $ev in
        7) # XCB_ENTER_NOTIFY
            if [ $SLOPPY -eq 1 ]; then
                wattr o $wid || {
                    fw $wid;
                }
            fi
            ;;
        16) # XCB_CREATE_NOTIFY
            case "$(wi name $wid)" in
                hud)
                    chwb -s 0 $wid;
                    chwso -l $wid;
                    ignw -s $wid;
                    ;;
                st*) cw -p $wid; ;;
            *) case "$(wi class $wid)" in
               *) # default
                    isFullscreen $wid && {
                        wtp 0 0 $(wattr w $WRT) $(wattr h $WRT) $wid;
                        chwso -r $wid;
                    }
                    wattr o $wid || {
                        fw $wid;
                    }
               ;;
               esac
               ;;
            esac
            ;;
        19) # XCB_MAP_NOTIFY
            case "$(wi name $wid)" in
            *) case "$(wi class $wid)" in
                dmenu)
                    chwso -r $wid;
                    ignw -s $wid;
                    ;;
                mpv)
                    chwb -s 0 $wid;
                    wtp $(wattr xywh $WRT);
                    # placew $wid;
                    ;;
               *) # default
                   blur;
               ;;
               esac
               ;;
            esac
            ;;
        17) # XCB_DESTROY_NOTIFY
            ;;
        18) # XCB_UNMAP_NOTIFY
            case "$(wi name $wid)" in
            *) case "$(wi class $wid)" in
               *) # default
                blur;
                wattr "$(pfw)" || fw prev;
               ;;
               esac
               ;;
            esac
            ;;
        28) # XCB_EVENT_MASK_PROPERTY_CHANGE
            case $atom in
                39) # XCB_ATOM_WM_NAME
                    echo "N%{F#$CAttn}$(wi title $wid)%{F-}" >$HUD_FIFO;
                    ;;
            esac
            ;;
    esac
done
