#!/bin/sh

. $WMRC
. util.sh

restart() {
    for prg in $XDG_CONFIG_HOME/hud/?*.sh; do
        pkill -x "$(basename $prg)";
    done
    exec $(realpath $0);
}
trap restart USR1;

output="";

if [ -f /tmp/hud.pid ]; then
    printf '%s\n' "hud is already running" >&2;
    exit $ERREXE;
fi

trap 'trap - TERM; rm /tmp/hud.pid; kill 0' INT TERM QUIT EXIT

test -e "$HUD_FIFO" && rm "$HUD_FIFO";
mkfifo "$HUD_FIFO";
echo $$ >/tmp/hud.pid;

for script in $XDG_CONFIG_HOME/hud/?*.sh ; do
    $script > "$HUD_FIFO" &
done

while read -r line; do
    case "$line" in
        T*) # Time
            time=" ${line#?} " ;;
        B*) # Battery
            bat=" ${line#?} " ;;
        W*) # Wifi
            net=" ${line#?} " ;;
        N*) # Notification
            notif=" ${line#?} " ;;
    esac
    printf "%s%s%s%s%s%s\n" \
        "%{l}" "%{A:menu-windows:} w %{A}" \
        "%{c}" "${time}" \
        "%{r}" "${notif} ${net} ${bat} ";
done < "$HUD_FIFO" |\
    lemonbar -n hud -d -gx${HUDH} -f 'Luxi Mono:size=10' \
             -B#dd${CBG} -F#${CFG} | sh &

wait;
