#!/bin/sh

. $WMRC
. ./util.sh
ARGS=""

reads curx curw -- wattr xw "$PFW";

test $# -ne 0 && e="$@" || e=lsw;
$e | grep -vs "$PFW" |\
while read wid; do
    reads winx winw -- wattr xw "$wid";
    test $(( winx + winw )) -lt $curx && continue;
    test $(( curx + curw )) -lt $winx && continue;
    echo $wid;
done
