#!/bin/sh

. $WMRC
. ./util.sh
ARGS=""

reads cury curh -- wattr yh "$PFW";

test $# -ne 0 && e="$@" || e=lsw;
$e | grep -vs "$PFW" |\
while read wid; do
    reads winy winh -- wattr yh "$wid";
    test $(( winy + winh )) -lt $cury && continue;
    test $(( cury + curh )) -lt $winy && continue;
    echo $wid;
done
