#!/bin/sh
# return a point In Regard To Window

. util.sh
ARGS="<tl|tr|bl|br|md> <wid>"

test $# -eq 2 || usage $ERRARG;
corner=$1; wid=$2;

reads wx wy ww wh -- wattr xywh $wid;

case $corner in
    tl*) x=$wx; y=$wy;                           ;;
    tr*) x=$((wx + ww)); y=$wy;                  ;;
    bl*) x=$wx; y=$((wy + wh));                  ;;
    br*) x=$((wx + ww)); y=$((wy + wh));         ;;
    md*) x=$((wx + ww / 2)); y=$((wy + wh / 2)); ;;
    *)  usage $ERRARG "Unknown argument: $1";    ;;
esac

printf '%s\t%s\n' $x $y;
