#!/bin/sh

set -o pipefail

DMENU_OPTS="-i -n -p w -h 20 -w 400 -l 10"

n=1;
{ lsw; lsw -u; } | tac | xargs wi -id title |\
grep -vE '_NET_WM_NAME:\s+not found' |\
while read -r wid wtitle; do
    printf '%s: %s (%s)\n' $n "${wtitle}" $wid;
    n=$((n + 1));
done | tee /tmp/wins_$$ | \
case $(wc -l) in
    1) notify "Only one window!";
        fw </tmp/wins_$$;
        ;;
    *) dmenu $DMENU_OPTS -fn 'Luxi Mono:size=10' </tmp/wins_$$ | \
       sed 's/.*(\(.*\))$/\1/' | xargs fw -p -r -m
        ;;
esac
