#!/usr/bin/env dash
# vim:ft=sh

. $WMRC

# TODO: better option handling & options
while [ "$(expr index "$1" -)" = 1 ]; do
    case $1 in
        -x*) bx=$(expr substr $1 3 4)  ;;
        -y*) by=$(expr substr $1 3 4)  ;;
        -w*) bw=$(expr substr $1 3 4)  ;;
        -h*) bh=$(expr substr $1 3 4)  ;;
        -t*) t=$(expr substr $1 3 10)  ;;
        -g*) exit $ERRARG              ;;
        -*)  lemonargs="$lemonargs $1" ;;
    esac
    shift;
done

mw=$(wattr w $WRT)
mh=$(wattr h $WRT)
bw=${bw:-200}
bh=${bh:-10}
bx=${bx:-$((mw - bw - 5))}
by=${by:-10}
t=${t:-2s}

{ echo $@ ; sleep $t ; } | \
    lemonbar -g${bw}x${bh}+${bx}+${by} $lemonargs -n NOTIFY
