#!/usr/bin/env dash
# vim:ft=sh

. $WMRC
PFW=$(pfw)

usage() {
    cat >&2 << EOF
    $(basename $0) <direction>
    Focuses the closest window in <direction>.
EOF
    return $ERRUSE
}

# TODO: wrap focus around screen
# TODO (maybe): only consider windows in <direction> from $PFW
_west() {
    case $1 in
        next)
            lsw | xargs wattr yxi | sort -nr | sed "0,/$PFW/d" | cut -d' ' -f3
            ;;
        first)
            lsw | xargs wattr yxi | sort -nr | grep -v $PFW | cut -d' ' -f3
            ;;
    esac
}
_east() {
    case $1 in
        next)
            lsw | xargs wattr yxi | sort -n  | sed "0,/$PFW/d" | cut -d' ' -f3
            ;;
        first)
            lsw | xargs wattr yxi | sort -n  | grep -v $PFW | cut -d' ' -f3
            ;;
    esac
}
_north() {
    case $1 in
        next)
            lsw | xargs wattr xyi | sort -nr | sed "0,/$PFW/d" | cut -d' ' -f3
            ;;
        first)
            lsw | xargs wattr xyi | sort -nr | grep -v $PFW | cut -d' ' -f3
            ;;
    esac
}
_south() {
    case $1 in
        next)
            lsw | xargs wattr xyi | sort -n  | sed "0,/$PFW/d" | cut -d' ' -f3
            ;;
        first)
            lsw | xargs wattr xyi | sort -n  | grep -v $PFW | cut -d' ' -f3
            ;;
    esac
}

# main
case $1 in
    h|west|left)  wid=$(_west next);  dir=_west  ;;
    j|south|down) wid=$(_south next); dir=_south ;;
    k|north|up)   wid=$(_north next); dir=_north ;;
    l|east|right) wid=$(_east next);  dir=_east  ;;
    *)
       usage "Unknown direction.";
       exit $ERRARG;
       ;;
esac

test -n "$wid" || wid=$($dir first);
wfocus $wid;
