#!/bin/sh
# Window Info

. $WMRC
ARGS="<query> <wid..>"
SHOW_ID=0;

test $# -gt 0 || usage $ERRARG;
test $1 = "-id" && { SHOW_ID=1; shift; }
query=$1; shift;

for wid in $@; do
    test $SHOW_ID -eq 1 && printf '%s    ' "$wid";
    if lsw -a | grep -q "$wid"; then
        case $query in
            name)
                xprop -id "$wid" WM_CLASS | cut -d\" -f2;
                ;;
            class)
                xprop -id "$wid" WM_CLASS | cut -d\" -f4;
                ;;
            pid)
                xprop -id "$wid" _NET_WM_PID | cut -d' ' -f3;
                ;;
            title)
                xprop -id "$wid" _NET_WM_NAME | cut -d\" -f2- | head -c -2;
                echo;
                ;;
        esac
        unset -v wid;
    else
        exit $ERRWIN;
    fi
done
