#!/bin/sh
# Window Under Point

. util.sh
ARGS="[<x> <y>]"

if [ $# -eq 0 ]; then
    reads x y -- wmp
else
    test $# -eq 2 || usage $ERRARG;
    x=$1; y=$2;
fi

for wid in $(lsw | tac); do
    reads wx wy ww wh -- wattr xywh $wid;
    test $wx -gt $x            && continue;
    test $wy -gt $y            && continue;
    test $(( wx + ww )) -lt $x && continue;
    test $(( wy + wh )) -lt $y && continue;
    echo "$wid";
    exit $SUCCESS;
    unset -v wid;
done

exit $ERRWIN;
